---
# tasks file for web-server
- name: install_nginx
  become: yes
  apt:
     name: nginx
     state: present

- name: template_nginx
  become: yes
  template: src=default.j2 dest=/etc/nginx/sites-available/default
